# url settings
url:
  # // is usually fine, but you can specify either http:// or https:// if you like
  protocol: //
  # fully qualified domain name of server
  domain: yoursite.com
  # path to Digraph installation should have leading/trailing slashes
  path: /

timezone: America/Denver

image:
  #gd, imagick or gmagick -- gd is the default because it's widely supported
  driver: gd

# Default contents of packages
package:
  defaults:
    fields:
      site_name: Digraph example site

# Generally if you want to move your storage/cache directories you should keep
# them somehow relative to paths.site
paths:
  storage: ${paths.site}/storage

# Template helper options
templates:
  # templates.theme can be either a single theme name or an array of theme names
  # that will have their css/js included after core code, in the given order
  theme: _digraph_dark
  # Additional paths can be added here, they will be used in the reverse of the
  # order they're listed here
  paths:
    site: ${paths.site}/templates
  twigconfig:
    cache: ${paths.cache}/twig

# Configure module directories for site
modules:
  sources:
    200-site: dir ${paths.site}/modules

# configure cache settings
cache:
  # factorycache caches the results of storage queries
  factorycache:
    threshold: 10 #ms duration a query must take to be cached
  # mungercache caches the results of munging layers
  mungercache:
    threshold: 10 #ms duration a munger must take to be cached
