# url settings
url:
  # most things will work with "//" but you need to specify either http or https
  # for url BBCode tags to work right.
  protocol: http://
  # fully qualified domain name of server
  domain: yoursite.com
  # path to Digraph installation should have leading/trailing slashes, if it's
  # the root of your domain name, a single slash is required
  path: /

timezone: America/Denver

image:
  #gd, imagick or gmagick -- gd is the default because it's widely supported
  driver: gd

# Default contents of packages
package:
  defaults:
    fields:
      site_name: Digraph example site

# Generally if you want to move your storage/cache directories you should keep
# them somehow relative to paths.site
paths:
  storage: ${paths.site}/storage

# It's helpful for a site to have its own media directory as well
media:
  paths:
    site: ${paths.site}/media

# Template helper options
templates:
  # templates.theme can be either a single theme name or an array of theme names
  # that will have their css/js included after core code, in the given order
  theme: [digraph-basic,digraph-colors-dark]
  # theme: [digraph-basic]
  # Additional paths can be added here, they will be used in the reverse of the
  # order they're listed here
  paths:
    site: ${paths.site}/templates
  twigconfig:
    cache: ${paths.cache}/twig

# Configure module directories for site
modules:
  sources:
    200-site: dir ${paths.site}/modules
    300-pdf: class Digraph\Modules\digraph_pdf\Module

# configure cache settings
cache:
  # factorycache caches the results of storage queries
  factorycache:
    threshold: 10 #ms duration a query must take to be cached
  # mungercache caches the results of munging layers
  mungercache:
    threshold: 10 #ms duration a munger must take to be cached
