paths:
    web: "${paths.base}/web"
    storage: "${paths.base}/storage"
    cache: "${paths.base}/cache"

files:
    path: "${paths.web}/files"
    url: /files

fs:
    links: false
    umask_file: 0117
    umask_dir: 0002

db:
    adapter: mysql
    charset: utf8
    sqlite_create_functions: true
    pdo_options: []

page:
    cachettl:
        _any: null
    browserttl:
        _any: null
