oauth2:
  providers:
    github:
      title: GitHub
      class: \League\OAuth2\Client\Provider\Github
      scope: ["user:email"]
    google:
      title: Google
      class: \League\OAuth2\Client\Provider\Google
      scope: ["userinfo.email"]
    facebook:
      title: Facebook
      class: \League\OAuth2\Client\Provider\Facebook
      scope: ["email"]
      config:
        graphApiVersion: v2.10