urls:
  protocol: http

locking:
  storage: db

errors:
  display_trace: true

cache:
  ttl: 10

files:
  ttl: 600
  css:
    minify: true
    sourcemap: true

images:
  ttl: 3600

theme:
  bundle_css: true
  bundle_js: true
  head_cache_ttl: 600

user_sources:
  cas:
    providers:
      demo:
        active: true
        name: Demo login provider
        mock_cas_user: true

cron:
  route_enabled: true