urls:
  protocol: http

errors:
  display_trace: true

cache:
  path: false # use system temp dir, so it's fast in a dev container
  ttl: 600

files:
  ttl: 600
  css:
    minify: true
    sourcemap: true

images:
  ttl: 3600

theme:
  bundle_css: true
  bundle_js: true
  head_cache_ttl: 600

user_sources:
  cas:
    providers:
      demo:
        active: true
        name: Demo login provider
        mock_cas_user: true
