page_types:
  default: \DigraphCMS\Content\Page
  page: \DigraphCMS\Content\Page

rich_media_types:
  aside: \DigraphCMS\RichMedia\Types\AsideRichMedia
  bookmark: \DigraphCMS\RichMedia\Types\BookmarkRichMedia
  content: \DigraphCMS\RichMedia\Types\ContentRichMedia
  file: \DigraphCMS\RichMedia\Types\FileRichMedia
  image: \DigraphCMS\RichMedia\Types\ImageRichMedia
  table: \DigraphCMS\RichMedia\Types\TableRichMedia
  zip: \DigraphCMS\RichMedia\Types\ZipRichMedia

search:
  response_index:
    interval: 86400

sidebar:
  default_state: true

cron:
  route_enabled: false
  poor_mans_cron: true
  time_limit: 1
  intervals:
    default: 12 hours
    frequent: 5 minutes
    halfhourly: 30 minutes
    hourly: 1 hour
    daily: 1 day
    weekly: 1 week
    biweekly: 2 weeks
    monthly: 1 month
    index_pages: 1 day
    index_plugins: 1 day
    maintenance: 4 hours
    maintenance_heavy: 1 day

maintenance:
  expire_locking_records: -7 days
  expire_defex_records: -3 days
  expire_cron_errors: -7 days
  expire_search_index: -30 days

cache:
  path: ${paths.base}/cache
  driver: \DigraphCMS\Cache\OpCache
  ttl: 300
  fuzz: 120
  dom_ttl: 600
  template_ttl: 600
  content_ttl: 600

email:
  enabled: true
  from: null
  categories:
    service:
      label: Service Emails
      description: Necessary emails regarding your account or the services provided by the website.
    wayback:
      label: Wayback Machine Emails
      description: Notifications of broken links generated by Wayback Machine system.

codemirror:
  dependencies:
    all:
      - addon/search/search
      - addon/search/searchcursor
      - addon/search/jump-to-line
      - addon/dialog/dialog
    mode/gfm/gfm:
      - addon/mode/overlay
      - mode/markdown/markdown
      - addon/edit/continuelist
      - mode/xml/xml
    mode/php/php:
      - mode/xml/xml
      - mode/javascript/javascript
      - mode/css/css
      - mode/htmlmixed/htmlmixed
      - mode/clike/clike
    mode/sass/sass:
      - mode/css/css
  modealias:
    php: text/x-php
    phphtml: application/x-httpd-php
  loadalias:
    phphtml: php
  config:
    gfm:
      gitHubSpice: false
      taskLists: false

theme:
  bundle_css: true
  bundle_js: true
  head_cache_ttl: 86400

# default filesystem settings
fs:
  links: false
  umask_file: 0117
  umask_dir: 0002

# default database is a SQLite file in paths.storage
db:
  adapter: sqlite
  name: "${paths.storage}/database"
  charset: utf8
  pdo_options: []
  sqlite:
    # whether to manually insert JSON functions into SQLite, default is on
    # because most servers don't have SQLite compiled with native JSON functions,
    # but if yours does you should turn this off for performance
    create_functions: true

# settings for automatic wayback machine tools
wayback:
  # default wayback status
  active: true
  # enter a list of emails that will be notified when a broken link is found
  notify_emails: []
  # maximum notification frequency per context URL
  notify_frequency: 604800
  # maximum number of checks to run per pageview
  max_checks: 10
  # maximum number of API calls to make per pageview
  max_api_calls: 10
  # how long to cache API call results
  api_cache_ttl: 30 days
  # how frequently to check if links are down
  check_ttl: 3600
  # how long to wait for checks to time out
  check_timeout: 5
  # how long to allow connection to time out
  check_timeout_connect: 1

# optionally enable using PHP session for holding authentication
# by default a custom cookie is used
php_session:
  enabled: false
  key: DigraphAuthentication

users:
  sources:
    oauth2: \DigraphCMS\Users\OAuth2UserSource
    cas: \DigraphCMS\Users\CASUserSource

usermenu:
  guest_signin: true

# configuration for user sources, including preset options so that some providers
# are ready to go just by providing their id and secret parameters
user_sources:
  oauth2:
    providers:
      github:
        name: GitHub
        class: \League\OAuth2\Client\Provider\Github
        scope:
          - "user:email"
      google:
        name: Google
        class: \League\OAuth2\Client\Provider\Google
        scope:
          - userinfo.email
      facebook:
        name: Facebook
        class: \League\OAuth2\Client\Provider\Facebook
        scope:
          - email
        config:
          graphApiVersion: v2.10
