page_types:
  page: \DigraphCMS\Content\Page

rich_media_types:
  bookmark: \DigraphCMS\RichMedia\Types\BookmarkRichMedia
  content: \DigraphCMS\RichMedia\Types\ContentRichMedia
  aside: \DigraphCMS\RichMedia\Types\AsideRichMedia
  file: \DigraphCMS\RichMedia\Types\FileRichMedia
  zip: \DigraphCMS\RichMedia\Types\MultiFileRichMedia
  table: \DigraphCMS\RichMedia\Types\TableRichMedia

cache:
  path: ${paths.base}/cache
  driver: \DigraphCMS\Cache\OpCache
  ttl: 300
  fuzz: 120

theme:
  bundle_css: true
  bundle_js: true
  head_cache_ttl: 86400

# default filesystem settings
fs:
  links: false
  umask_file: 0117
  umask_dir: 0002

# default database is a SQLite file in paths.storage
db:
  adapter: sqlite
  name: "${paths.storage}/database"
  charset: utf8
  pdo_options: []
  sqlite:
    # whether to manually insert JSON functions into SQLite, default is on
    # because most servers don't have SQLite compiled with native JSON functions,
    # but if yours does you should turn this off for performance
    create_functions: true

# settings for automatic wayback machine tools
wayback:
  # maximum number of checks to run per pageview
  max_checks: 5
  # maximum number of API calls to make per pageview
  max_api_calls: 10
  # how long to cache API call results
  api_cache_ttl: 30 days
  # how frequently to check if links are down
  check_ttl: 86400
  # how long to wait for checks to time out
  check_ttl: 5
  # how long to allow connection to time out
  check_timeout_connect: 1

# optionally enable using PHP session for holding authentication
# by default a custom cookie is used
php_session:
  enabled: false
  key: DigraphAuthentication

users:
  sources:
    oauth2: \DigraphCMS\Users\OAuth2UserSource
    cas: \DigraphCMS\Users\CASUserSource

usermenu:
  guest_signin: true

# configuration for user sources, including preset options so that some providers
# are ready to go just by providing their id and secret parameters
user_sources:
  oauth2:
    providers:
      github:
        name: GitHub
        class: \League\OAuth2\Client\Provider\Github
        scope:
          - 'user:email'
      google:
        name: Google
        class: \League\OAuth2\Client\Provider\Google
        scope:
          - userinfo.email
      facebook:
        name: Facebook
        class: \League\OAuth2\Client\Provider\Facebook
        scope:
          - email
        config:
          graphApiVersion: v2.10
