page_types:
  default: \DigraphCMS\Content\Page
  page: \DigraphCMS\Content\Page

rich_media_types:
  aside: \DigraphCMS\RichMedia\Types\AsideRichMedia
  bookmark: \DigraphCMS\RichMedia\Types\BookmarkRichMedia
  content: \DigraphCMS\RichMedia\Types\ContentRichMedia
  file: \DigraphCMS\RichMedia\Types\FileRichMedia
  image: \DigraphCMS\RichMedia\Types\ImageRichMedia
  table: \DigraphCMS\RichMedia\Types\TableRichMedia
  zip: \DigraphCMS\RichMedia\Types\ZipRichMedia

exception_log:
  notify_emails: []
  notify_frequency: 3600

curl:
  fallback_cafile: null # Allow a specific fallback CA file to be used
  use_fallback_cafile: false # Use built-in fallback CA file instead of relying on server's config

search:
  response_index:
    interval: 86400

sidebar:
  default_state: true

cron:
  route_enabled: false
  poor_mans_cron: true
  time_limit: 1
  intervals:
    default: 12 hours
    frequent: 5 minutes
    email: 5 minutes
    halfhourly: 30 minutes
    hourly: 1 hour
    daily: 1 day
    weekly: 1 week
    biweekly: 2 weeks
    monthly: 1 month
    index_pages: 1 day
    index_plugins: 1 day
    maintenance: 4 hours
    maintenance_heavy: 1 day
    wayback: 15 minutes

maintenance:
  expire_locking_records: -7 days
  expire_defex_records: -3 days
  expire_cron_errors: -7 days
  expire_search_index: -14 days

cache:
  path: ${paths.base}/cache
  driver: \DigraphCMS\Cache\OpCache
  ttl: 300
  fuzz: 120
  dom_ttl: 600
  template_ttl: 600
  content_ttl: 600

email:
  header_width: 596
  body_width: 576
  enabled: true
  enabled_for: []
  from: null
  cron_time: 30 # seconds to allow sending email for during cron
  cron_count: 1000 # maximum number of queued emails to send in cron run
  use_smtp: false
  smtp:
    host: null
    auth: false # whether to use username and password
    user: null
    pass: null
    autotls: true
    security: null # either TLS for implicit or STARTTLS for explicit
    port: null # will be auto set most of the time
    options: null # see PHPMailer docs for the available options here
  service_categories:
    service: true
  categories:
    service:
      label: Service Emails
      description: Necessary emails regarding your account or the services provided by the website.
    wayback:
      label: Wayback Machine Emails
      description: Notifications of broken links generated by Wayback Machine system.

codemirror:
  dependencies:
    all:
      - addon/search/search
      - addon/search/searchcursor
      - addon/search/jump-to-line
      - addon/dialog/dialog
    mode/gfm/gfm:
      - addon/mode/overlay
      - mode/markdown/markdown
      - addon/edit/continuelist
      - mode/xml/xml
    mode/php/php:
      - mode/xml/xml
      - mode/javascript/javascript
      - mode/css/css
      - mode/htmlmixed/htmlmixed
      - mode/clike/clike
    mode/sass/sass:
      - mode/css/css
  modealias:
    php: text/x-php
    phphtml: application/x-httpd-php
  loadalias:
    phphtml: php
  config:
    gfm:
      gitHubSpice: false
      taskLists: false
    yaml:
      tabSize: 2

theme:
  bundle_css: true
  bundle_js: true
  head_cache_ttl: 86400

# default filesystem settings
fs:
  links: false
  umask_file: 0117
  umask_dir: 0002

# default database is a SQLite file in paths.storage
db:
  adapter: sqlite
  name: "${paths.storage}/database"
  charset: utf8
  pdo_options: []
  sqlite:
    # whether to manually insert JSON functions into SQLite, default is on
    # because most servers don't have SQLite compiled with native JSON functions,
    # but if yours does you should turn this off for better performance
    create_functions: true

# settings for automatic wayback machine tools
wayback:
  # default wayback status
  active: true
  # enter a list of emails that will be notified when a broken link is found
  notify_emails: []
  # maximum notification frequency per context URL
  notify_frequency: 2592000 # 30 days
  # how long to cache API call results
  api_ttl: 2592000 # 30 days
  # how long to cache notfound API call results
  api_notfound_ttl: 7776000 # 90 days
  # how frequently to retry failed API calls
  api_error_ttl: 3600 # hourly
  # how long to cache URL status checks
  check_ttl: 86400 # 1 day
  # how long to cache status checks when the URL is down
  check_notfound_ttl: 3600 # hourly

# optionally enable using PHP session for holding authentication
# by default a custom cookie is used
php_session:
  enabled: false
  key: DigraphAuthentication

users:
  sources:
    oauth2: \DigraphCMS\Users\OAuth2UserSource
    cas: \DigraphCMS\Users\CASUserSource

usermenu:
  guest_signin: true

# configuration for user sources, including preset options so that some providers
# are ready to go just by providing their id and secret parameters
user_sources:
  oauth2:
    providers:
      github:
        name: GitHub
        class: \League\OAuth2\Client\Provider\Github
        scope:
          - "user:email"
      google:
        name: Google
        class: \League\OAuth2\Client\Provider\Google
        scope:
          - userinfo.email
      facebook:
        name: Facebook
        class: \League\OAuth2\Client\Provider\Facebook
        scope:
          - email
        config:
          graphApiVersion: v2.10
