name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v6
      with:
        php_extensions: gd
    - uses: php-actions/phpstan@v3
      with:
        path: src/
        memory_limit: 128M
        php_extensions: gd
